#! /bin/bash

IMAGE_NAME="kmubigdata/ubuntu-hadoop"
DOCKER_RUN="sudo docker run -dit --network $1 --name"
MASTER_OPTION="--cpu-shares 1024 --memory 12g"
SLAVE_OPTION="--cpu-shares 1024 --memory 6g --storage-opt size=300G "
MASTER_COMMAND="$DOCKER_RUN master $MASTER_OPTION"
COMMAND_LAST="$IMAGE_NAME /bin/bash"

numOfContainers=1

if [[ -z "$4" ]]; then
        echo "-----------------------------------------------------------------"
        echo "Format is wrong"
        echo "./run_hadoop [network-name] [want-master] [slave-from] [slave-to]"
        echo "ex) ./run_hadoop my-net 1 1 5"
        echo "Overlay network is my-net, 0 for creating master container but 1, slave from 1, slave to 5"
        echo "-----------------------------------------------------------------"
        exit 0
fi

if [ $2 == 0 ]; then
        MASTER_COMMAND="$MASTER_COMMAND $COMMAND_LAST"
        $MASTER_COMMAND
fi

numOfContainers=$3

while [ $numOfContainers != $(($4+1)) ];
do
        SLAVE_COMMAND="$DOCKER_RUN slave$numOfContainers $SLAVE_OPTION $COMMAND_LAST"
        $SLAVE_COMMAND
        numOfContainers=$(($numOfContainers+1))
done

