#! /bin/bash

NETWORK=$2

MASTER_COMMAND="sudo docker run -it --name master --network $1 --ip 10.0.2.2 -p 8088:8088 -p 8042:8042 -p 8085:8080 -p 4040:4040 -p 7077:7077 -p 2022:22 --add-host=master:10.0.2.2 --cpu-shares 1024 --memory 12g"
SLAVE_FRONT="sudo docker run -it --name"
SLAVE_COMMAND=""
COMMAND_LAST="kmubigdata/ubuntu-hadoop /bin/bash"
SLAVE="slave"
ADDHOST='--add-host='
IP="10.0.2."

numOfContainers=1
numOfAddHosts=1
numOfCores=1
coreNumber=1
if [[ -z "$5" ]]; then
	echo "format is wrong"
	echo "./run_hadoop network-name want-master slave-from slave-to number-of-hosts"
	echo "ex) ./run_hadoop my-net 1 1 5 10"
	echo "network is my-net, need master container, slave from 1, slave to 5, number of hosts=10"
	exit 0
fi
	


if [ $2 == 1 ]; then
	while [ $numOfAddHosts != $(($5+1)) ];
	do
		MASTER_COMMAND="$MASTER_COMMAND $ADDHOST$SLAVE$numOfAddHosts:$IP$(($numOfAddHosts+2))"
		numOfAddHosts=$(($numOfAddHosts+1))
	done
	MASTER_COMMAND="$MASTER_COMMAND $COMMAND_LAST"
	$MASTER_COMMAND
fi

numOfContainers=$3
while [ $numOfContainers != $(($4+1)) ];
do
	SLAVE_COMMAND="$SLAVE_FRONT spark-slave$numOfContainers --network $1 --ip $IP$(($numOfContainers+2)) --memory 6g --cpu-shares 1024 --storage-opt size=300G --add-host=master:10.0.2.2"
	numOfAddHosts=1
	while [ $numOfAddHosts != $(($5+1)) ];
	do
        	SLAVE_COMMAND="$SLAVE_COMMAND $ADDHOST$SLAVE$numOfAddHosts:$IP$(($numOfAddHosts+2))"
       		numOfAddHosts=$(($numOfAddHosts+1))
	done

        numOfCores=1

	$SLAVE_COMMAND $COMMAND_LAST
	SLAVE_COMMAND=''
	numOfContainers=$(($numOfContainers+1))
	coreNumber=$(($coreNumber+1))
done
